name: Build EKS cluster plugin

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Makefile
      run: make plugin

    - name: Publish to artifact
      uses: actions/upload-artifact@v4
      with:
        name: dss-plugin-eks-clusters
        path: dist/*.zip
        retention-days: 2

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_name: "vnext"
        target_commitish: master
        body: |
          This is a pre-release for the next version of the DSS EKS plugin.
        draft: true
        prerelease: true
        generate_release_notes: false

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/*.zip"
