name: Build EKS cluster plugin

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Commit hash or branch to release (optional, defaults to master)'
        required: false

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.target || 'master' }}

    - name: Check for make
      run: make --version

    - name: Run Makefile
      run: make plugin

    - name: Publish to artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: dist/*.zip
