name: Build EKS cluster plugin

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Makefile
      run: make plugin

    - name: Publish to artifact
      uses: actions/upload-artifact@v4
      with:
        name: dss-plugin-eks-clusters
        path: dist/*.zip
        retention-days: 2
